const LAYOUT_PANELS = Object.freeze({
  CHAT_DEFAULT_WIDTH: 40,
  CHAT_MIN_WIDTH: 20,
  EDITOR_DEFAULT_WIDTH: 60,
  EDITOR_MIN_WIDTH: 40,
  MAIN_MIN_WIDTH: 320,
  SIDEBAR_COLLAPSED_WIDTH: 48,
  SIDEBAR_DEFAULT_WIDTH: 256,
  SIDEBAR_MAX_WIDTH: '50%',
  SIDEBAR_MAX_WIDTH_PX: 600,
  SIDEBAR_MIN_WIDTH: 225,
});

export default LAYOUT_PANELS;
