const LAYOUT_PANELS = Object.freeze({
  MAIN_MIN_WIDTH: 320,
  SIDEBAR_AUTHOR_BADGE_VISIBLE_WIDTH: 225,
  SIDEBAR_COLLAPSED_WIDTH: 48,
  SIDEBAR_DEFAULT_WIDTH: 256,
  SIDEBAR_MAX_WIDTH: '50%',
  SIDEBAR_MAX_WIDTH_PX: 600,
  SIDEBAR_MIN_WIDTH: 180,
});

export default LAYOUT_PANELS;
